// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_RYw4ZaQs8GD_wJs_bGsNJPjpkKyL4yU',
    appId: '1:683499127522:web:97e1618cef14c36dc014bb',
    messagingSenderId: '683499127522',
    projectId: 'garuda-1ba07',
    authDomain: 'garuda-1ba07.firebaseapp.com',
    databaseURL: 'https://garuda-1ba07-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'garuda-1ba07.firebasestorage.app',
    measurementId: 'G-32PHS5XD9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI14SfgeCZEqo8LOVbTh8fxhNz4KZRk64',
    appId: '1:683499127522:android:7c0a5293ff4b19c8c014bb',
    messagingSenderId: '683499127522',
    projectId: 'garuda-1ba07',
    databaseURL: 'https://garuda-1ba07-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'garuda-1ba07.firebasestorage.app',
  );

}