// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkdNjHCo7gahfjEJRcGz64EQwsIkQYkFY',
    appId: '1:129760746257:web:46f4e6fa1a22ce7deb8ab0',
    messagingSenderId: '129760746257',
    projectId: 'vkhillseva',
    authDomain: 'vkhillseva.firebaseapp.com',
    databaseURL: 'https://vkhillseva-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vkhillseva.firebasestorage.app',
    measurementId: 'G-QVKKNHS8ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcKPvG97ruORaBB0Qc8sVe4et9mjxe_V4',
    appId: '1:129760746257:android:790024f3a0cd91aeeb8ab0',
    messagingSenderId: '129760746257',
    projectId: 'vkhillseva',
    databaseURL: 'https://vkhillseva-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vkhillseva.firebasestorage.app',
  );

}